Locale: zh_cn.yml
#语言设置 文件需位于 Locale/ 下

Sign:
  UpdateMillis: 500
  #加入告示牌更新频率，默认 500，单位为毫秒

Item: #设置使用物品，所设置项必须存在于 枚举类 Material下，若不存在将会使用默认的 Material
  LEAVE_GAME: RED_BED #离开游戏
  NAVIGATION_BACKGROUND: BLACK_STAINED_GLASS_PANE #导航栏背景
  NAVIGATION_PREVIOUS: RED_WOOL #导航栏——上一页
  NAVIGATION_COUNTDOWN: NETHER_STAR #导航栏——选择被提问者倒计时
  NAVIGATION_COUNTDOWN_VOTE: NETHER_STAR #导航栏——投票倒计时
  NAVIGATION_NEXT: GREEN_WOOL #导航栏——下一页
  END_ANSWER: REDSTONE_BLOCK #结束回答
  GUESS_WORD_GUI_PLACEHOLDER: PAPER #猜词界面占位物品

ItemSlot: #设置物品在玩家背包的哪个格子
  LEAVE_GAME: 8 #离开游戏
  END_ANSWER: 4 #结束回答
  INIT_VOTE: 8 #发起投票
  INIT_GUESS_WORD: 8 #猜词

#游戏内聊天格式
GameChatFormat: "&8[&7%GAME%&8] &7%PLAYER% &8> &r%MESSAGE%"

#设置词语
Word:
  - 飞机
  - 银行
  - 电影院
  - 汽车
  - 电脑
  - 潜艇
  - 海豚
  - 海带
  - 海洋
  - 沙丁鱼
  - 插件
  - 玩家
  - 空调
  - 裁判
  - 我是警长
  - 警长
  - CPU
  - GPU
  - APU
  - 爸爸
  - 妈妈
  - 爷爷
  - 奶奶
  - 叔叔
  - 阿姨
  - 表哥
  - 表弟
  - 表姐
  - 表妹
  - 姑姑
  - 婶婶
  - 外甥
  - 舅舅
  - 哥哥
  - 姐姐
  - 妹妹
  - 小姨
  - 大姨
  - 七大姑八大姨